"""initial_schema_all_tables

Revision ID: 7375b6ea1e47
Revises: 
Create Date: 2026-07-15 18:41:23.780942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7375b6ea1e47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('source_file_ref', sa.String(length=512), nullable=True),
    sa.Column('extraction_status', sa.String(length=32), nullable=False),
    sa.Column('invoice_status', sa.String(length=32), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('po_reference', sa.String(length=64), nullable=True),
    sa.Column('contract_reference', sa.String(length=64), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_terms', sa.String(length=128), nullable=True),
    sa.Column('raw_extraction_payload', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_contract_reference'), ['contract_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_po_reference'), ['po_reference'], unique=False)

    op.create_table('vendors',
    sa.Column('vendor_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=254), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_vendor_code'), ['vendor_code'], unique=True)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=True),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('po_reference', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_po_reference'), ['po_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_vendor_name'), ['vendor_name'], unique=False)

    op.create_table('contracts',
    sa.Column('contract_reference', sa.String(length=64), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('discount_term_raw', sa.String(length=64), nullable=True),
    sa.Column('discount_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('discount_days', sa.Integer(), nullable=True),
    sa.Column('net_days', sa.Integer(), nullable=True),
    sa.Column('approval_threshold', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_contract_reference'), ['contract_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_contracts_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('discount_recommendations',
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('discount_days', sa.Integer(), nullable=True),
    sa.Column('net_days', sa.Integer(), nullable=True),
    sa.Column('invoice_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('annualized_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('hurdle_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('recommendation', sa.String(length=32), nullable=False),
    sa.Column('discount_date', sa.Date(), nullable=True),
    sa.Column('window_missed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discount_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discount_recommendations_invoice_id'), ['invoice_id'], unique=True)

    op.create_table('exception_records',
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('human_action', sa.String(length=32), nullable=True),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exception_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exception_records_invoice_id'), ['invoice_id'], unique=True)

    op.create_table('invoice_line_items',
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_line_items_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('match_results',
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('vendor_known', sa.Boolean(), nullable=False),
    sa.Column('po_resolved', sa.Boolean(), nullable=False),
    sa.Column('contract_resolved', sa.Boolean(), nullable=False),
    sa.Column('quantities_match', sa.Boolean(), nullable=False),
    sa.Column('prices_match', sa.Boolean(), nullable=False),
    sa.Column('total_matches', sa.Boolean(), nullable=False),
    sa.Column('approval_satisfied', sa.Boolean(), nullable=False),
    sa.Column('overall_passed', sa.Boolean(), nullable=False),
    sa.Column('total_variance_abs', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total_variance_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('line_item_details_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_results_invoice_id'), ['invoice_id'], unique=True)

    op.create_table('payment_schedules',
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_taken', sa.Boolean(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_schedules_invoice_id'), ['invoice_id'], unique=True)

    op.create_table('purchase_orders',
    sa.Column('po_number', sa.String(length=64), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('po_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('approval_threshold', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_po_number'), ['po_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_orders_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('contract_line_items',
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_line_items_contract_id'), ['contract_id'], unique=False)

    op.create_table('exception_reasons',
    sa.Column('exception_record_id', sa.String(length=36), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('supporting_data_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exception_record_id'], ['exception_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exception_reasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exception_reasons_exception_record_id'), ['exception_record_id'], unique=False)

    op.create_table('po_line_items',
    sa.Column('purchase_order_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('po_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_po_line_items_purchase_order_id'), ['purchase_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('po_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_po_line_items_purchase_order_id'))

    op.drop_table('po_line_items')
    with op.batch_alter_table('exception_reasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exception_reasons_exception_record_id'))

    op.drop_table('exception_reasons')
    with op.batch_alter_table('contract_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_line_items_contract_id'))

    op.drop_table('contract_line_items')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_po_number'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('payment_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_schedules_invoice_id'))

    op.drop_table('payment_schedules')
    with op.batch_alter_table('match_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_results_invoice_id'))

    op.drop_table('match_results')
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_line_items_invoice_id'))

    op.drop_table('invoice_line_items')
    with op.batch_alter_table('exception_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exception_records_invoice_id'))

    op.drop_table('exception_records')
    with op.batch_alter_table('discount_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discount_recommendations_invoice_id'))

    op.drop_table('discount_recommendations')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_contract_reference'))

    op.drop_table('contracts')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_vendor_name'))
        batch_op.drop_index(batch_op.f('ix_audit_events_po_reference'))
        batch_op.drop_index(batch_op.f('ix_audit_events_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_audit_events_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))

    op.drop_table('audit_events')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_vendor_code'))

    op.drop_table('vendors')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_po_reference'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_contract_reference'))

    op.drop_table('invoices')
    # ### end Alembic commands ###
